# Generated by Django 3.1.2 on 2020-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201105_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
